# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b17b18b1aeb876934f7f4aab69fb97af752f2d5ad805b7faa95f5eb98ec282b402f8ac181fadb0aa0e7ee7ecb0d7d94275ed7fe50b8b2e5fa47a512fa184e7f2

test:
  secret_key_base: 4966d1fadf9e3b82fab31daabaeb63036e0936b1aac845770dcf2f5a2b0a1ca54e52ef73780d2c89738313299b59788e6c26289d88296b287a7f648d351d8608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
